# Generated by Django 5.2.5 on 2025-08-30 02:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('executions', '0001_initial'),
        ('hosts', '0001_initial'),
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnuData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_key', models.TextField()),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_raw', models.JSONField(blank=True, null=True)),
                ('collected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(db_column='execution_id', on_delete=django.db.models.deletion.CASCADE, to='executions.execution')),
                ('oid', models.ForeignKey(db_column='oid_id', on_delete=django.db.models.deletion.CASCADE, to='oids.oid')),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, to='hosts.olt')),
            ],
            options={
                'verbose_name': 'ONU Data',
                'verbose_name_plural': 'ONU Data',
                'db_table': 'onu_data',
            },
        ),
        migrations.CreateModel(
            name='SnmpJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('descubrimiento', 'descubrimiento'), ('walk', 'walk'), ('get', 'get'), ('table', 'table'), ('bulk', 'bulk')], default='descubrimiento', max_length=20)),
                ('interval_raw', models.CharField(blank=True, help_text='Ej: 30s, 5m, 1h', max_length=16)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, help_text='Intervalo en segundos', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('cron_expr', models.CharField(blank=True, max_length=120, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('max_retries', models.PositiveSmallIntegerField(default=2)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=120)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.PROTECT, to='brands.brand')),
                ('oid', models.ForeignKey(db_column='oid_id', on_delete=django.db.models.deletion.PROTECT, related_name='snmp_jobs', to='oids.oid')),
            ],
            options={
                'verbose_name': 'Tarea SNMP',
                'verbose_name_plural': 'Tareas SNMP',
                'db_table': 'snmp_jobs',
                'ordering': ['next_run_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SnmpJobHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('queue_name', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, related_name='job_host_links', to='hosts.olt')),
                ('snmp_job', models.ForeignKey(db_column='snmp_job_id', on_delete=django.db.models.deletion.CASCADE, related_name='job_hosts', to='snmp_jobs.snmpjob')),
            ],
            options={
                'verbose_name': 'OLT en Tarea',
                'verbose_name_plural': 'OLTs en Tarea',
                'db_table': 'snmp_job_hosts',
            },
        ),
        migrations.AddField(
            model_name='snmpjob',
            name='olts',
            field=models.ManyToManyField(related_name='snmp_jobs', through='snmp_jobs.SnmpJobHost', to='hosts.olt'),
        ),
        migrations.AddIndex(
            model_name='snmpjobhost',
            index=models.Index(fields=['olt', 'snmp_job'], name='snmp_job_ho_olt_id_c3bc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpjobhost',
            index=models.Index(fields=['snmp_job'], name='snmp_job_ho_snmp_jo_899cd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snmpjobhost',
            unique_together={('snmp_job', 'olt')},
        ),
        migrations.AddIndex(
            model_name='snmpjob',
            index=models.Index(fields=['next_run_at'], name='snmp_jobs_next_ru_a2f261_idx'),
        ),
    ]
