# Generated by Django 5.2.5 on 2025-09-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_jobs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnuData',
        ),
    ]
