# Generated by Django 5.2.5 on 2025-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_jobs', '0002_remove_onu_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpjob',
            name='retry_delay_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
