# Generated by Django 4.2.16 on 2025-10-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_jobs', '0003_change_retry_delay_to_30s'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpjobhost',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='Última ejecución para ESTA OLT', null=True),
        ),
        migrations.AddField(
            model_name='snmpjobhost',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Próxima ejecución para ESTA OLT específica', null=True),
        ),
    ]
