# Generated by Django 4.2.16 on 2025-10-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_jobs', '0004_snmpjobhost_last_run_at_snmpjobhost_next_run_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snmpjobhost',
            index=models.Index(fields=['next_run_at'], name='snmp_job_ho_next_ru_52b7e5_idx'),
        ),
    ]
