# Generated by Django 4.2.16 on 2025-11-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_alter_olt_modelo'),
        ('snmp_jobs', '0005_snmpjobhost_snmp_job_ho_next_ru_52b7e5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLTWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Workflow SNMP', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('auto', 'Automático'), ('light', 'Claro'), ('dark', 'Oscuro')], default='auto', help_text='Preferencia de tema para la UI Airflow-like.', max_length=16)),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Metadata de layout (zoom, pan, configuraciones del canvas).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='hosts.olt')),
            ],
            options={
                'verbose_name': 'Workflow SNMP por OLT',
                'verbose_name_plural': 'Workflows SNMP por OLT',
                'db_table': 'snmp_olt_workflows',
            },
        ),
        migrations.CreateModel(
            name='TaskFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identificador interno (ej. discovery_onu_huawei)', max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('module_path', models.CharField(help_text='Ruta del módulo Python (ej. snmp_jobs.workers.discovery)', max_length=255)),
                ('callable_name', models.CharField(help_text='Nombre de la función dentro del módulo (ej. run_discovery)', max_length=120)),
                ('function_type', models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('get', 'SNMP GET'), ('auxiliar', 'Auxiliar')], db_index=True, default='get', max_length=20)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Función SNMP',
                'verbose_name_plural': 'Funciones SNMP',
                'db_table': 'snmp_task_functions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único (ej. discovery-huawei-onu)', max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('default_interval_seconds', models.PositiveIntegerField(default=300)),
                ('default_priority', models.PositiveSmallIntegerField(choices=[(1, 'Discovery'), (2, 'GET crítico'), (3, 'GET estándar')], default=3)),
                ('default_retry_policy', models.JSONField(blank=True, default=dict)),
                ('default_run_options', models.JSONField(blank=True, default=dict)),
                ('default_color', models.CharField(default='#1f77b4', help_text='Color hexadecimal para la UI (tema claro/oscuro).', max_length=16)),
                ('default_icon', models.CharField(blank=True, help_text='Emoji o icono corto para representar la tarea.', max_length=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='snmp_jobs.taskfunction')),
            ],
            options={
                'verbose_name': 'Plantilla de Tarea SNMP',
                'verbose_name_plural': 'Plantillas de Tareas SNMP',
                'db_table': 'snmp_task_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre visible en la UI (editable por OLT).', max_length=150)),
                ('interval_seconds', models.PositiveIntegerField(help_text='Intervalo específico para este nodo.')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Discovery'), (2, 'GET crítico'), (3, 'GET estándar')], db_index=True, default=3)),
                ('enabled', models.BooleanField(default=True)),
                ('position_x', models.DecimalField(decimal_places=2, default=0, help_text='Posición X en el canvas Airflow-like.', max_digits=7)),
                ('position_y', models.DecimalField(decimal_places=2, default=0, help_text='Posición Y en el canvas Airflow-like.', max_digits=7)),
                ('color_override', models.CharField(blank=True, help_text='Color específico para el nodo (opcional).', max_length=16)),
                ('icon_override', models.CharField(blank=True, help_text='Icono específico para el nodo (opcional).', max_length=8)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='snmp_jobs.tasktemplate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='snmp_jobs.oltworkflow')),
            ],
            options={
                'verbose_name': 'Nodo de Workflow SNMP',
                'verbose_name_plural': 'Nodos de Workflow SNMP',
                'db_table': 'snmp_workflow_nodes',
                'ordering': ['workflow', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('secuencial', 'Secuencial'), ('condicional', 'Condicional')], default='secuencial', max_length=20)),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Condiciones adicionales para ejecución (solo para condicional).')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downstream_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_edges', to='snmp_jobs.workflownode')),
                ('upstream_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_edges', to='snmp_jobs.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='snmp_jobs.oltworkflow')),
            ],
            options={
                'verbose_name': 'Dependencia de Workflow SNMP',
                'verbose_name_plural': 'Dependencias de Workflow SNMP',
                'db_table': 'snmp_workflow_edges',
                'unique_together': {('workflow', 'upstream_node', 'downstream_node')},
            },
        ),
    ]
