# Generated by Django 4.2.16 on 2025-11-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_jobs', '0006_oltworkflow_taskfunction_tasktemplate_workflownode_and_more'),
    ]

    operations = [
    ]
