# Generated by Django 4.2.16 on 2025-11-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_jobs', '0007_add_workflow_node_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único de la plantilla', max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Workflow',
                'verbose_name_plural': 'Plantillas de Workflow',
                'db_table': 'snmp_workflow_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_sync', models.BooleanField(default=True, help_text='Si True, los cambios en la plantilla se propagan automáticamente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vinculación Plantilla-Workflow',
                'verbose_name_plural': 'Vinculaciones Plantilla-Workflow',
                'db_table': 'snmp_workflow_template_links',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identificador único del nodo (ej: discover.60min, get.description.10min). Se usa para vincular automáticamente con nodos existentes en workflows.', max_length=150)),
                ('name', models.CharField(help_text='Nombre descriptivo del nodo', max_length=150)),
                ('interval_seconds', models.PositiveIntegerField(default=300)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Discovery'), (2, 'GET crítico'), (3, 'GET estándar')], default=3)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('position_x', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('position_y', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('color_override', models.CharField(blank=True, max_length=16)),
                ('icon_override', models.CharField(blank=True, max_length=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nodo de Plantilla',
                'verbose_name_plural': 'Nodos de Plantilla',
                'db_table': 'snmp_workflow_template_nodes',
                'ordering': ['template', 'priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workflownode',
            name='key',
            field=models.CharField(blank=True, help_text='Identificador único del nodo (ej: discover.60min, get.description.10min). Si coincide con una key de plantilla vinculada, se vincula automáticamente.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='override_enabled',
            field=models.BooleanField(default=False, help_text='Si True, el estado enabled fue sobrescrito manualmente'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='override_interval',
            field=models.BooleanField(default=False, help_text='Si True, el intervalo fue sobrescrito manualmente y no se actualiza desde la plantilla'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='override_parameters',
            field=models.BooleanField(default=False, help_text='Si True, los parámetros fueron sobrescritos manualmente'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='override_priority',
            field=models.BooleanField(default=False, help_text='Si True, la prioridad fue sobrescrita manualmente'),
        ),
        migrations.AlterUniqueTogether(
            name='workflownode',
            unique_together={('workflow', 'key')},
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'key'], name='snmp_workfl_workflo_68024e_idx'),
        ),
        migrations.AddField(
            model_name='workflowtemplatenode',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_template_nodes', to='snmp_jobs.tasktemplate'),
        ),
        migrations.AddField(
            model_name='workflowtemplatenode',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_nodes', to='snmp_jobs.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowtemplatelink',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_links', to='snmp_jobs.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowtemplatelink',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_links', to='snmp_jobs.oltworkflow'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='template_node',
            field=models.ForeignKey(blank=True, help_text='Nodo de plantilla del cual proviene este nodo (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_nodes', to='snmp_jobs.workflowtemplatenode'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['template_node'], name='snmp_workfl_templat_15bcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplatenode',
            index=models.Index(fields=['template', 'key'], name='snmp_workfl_templat_bf0681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtemplatenode',
            unique_together={('template', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowtemplatelink',
            unique_together={('template', 'workflow')},
        ),
    ]
