# Generated by Django 4.2.16 on 2025-11-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('olt_models', '0002_add_sample_models'),
        ('oids', '0008_alter_oid_marca_alter_oid_modelo'),
        ('snmp_jobs', '0009_generate_keys_for_existing_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplatenode',
            name='marca',
            field=models.ForeignKey(blank=True, db_column='marca_id', help_text='Marca específica para este nodo. Si está vacío, aplica a todas las marcas.', null=True, on_delete=django.db.models.deletion.PROTECT, to='brands.brand'),
        ),
        migrations.AddField(
            model_name='workflowtemplatenode',
            name='modelo',
            field=models.ForeignKey(blank=True, db_column='modelo_id', help_text='Modelo específico para este nodo. Si está vacío, aplica a todos los modelos de la marca.', null=True, on_delete=django.db.models.deletion.PROTECT, to='olt_models.oltmodel'),
        ),
        migrations.AddField(
            model_name='workflowtemplatenode',
            name='oid_discovery',
            field=models.ForeignKey(blank=True, db_column='oid_discovery_id', help_text='OID para operaciones de descubrimiento (solo para tareas de tipo discovery).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_template_nodes_discovery', to='oids.oid'),
        ),
        migrations.AddField(
            model_name='workflowtemplatenode',
            name='oid_get',
            field=models.ForeignKey(blank=True, db_column='oid_get_id', help_text='OID para operaciones GET (solo para tareas de tipo GET).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_template_nodes_get', to='oids.oid'),
        ),
    ]
