# Generated by Django 4.2.16 on 2025-11-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0008_alter_oid_marca_alter_oid_modelo'),
        ('snmp_jobs', '0010_add_marca_modelo_oids_to_template_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtemplatenode',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='workflowtemplatenode',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='workflowtemplatenode',
            name='oid_discovery',
        ),
        migrations.RemoveField(
            model_name='workflowtemplatenode',
            name='oid_get',
        ),
        migrations.RemoveField(
            model_name='workflowtemplatenode',
            name='task_template',
        ),
        migrations.AddField(
            model_name='workflowtemplatenode',
            name='oid',
            field=models.ForeignKey(blank=True, db_column='oid_id', help_text='OID SNMP que define marca, modelo y tipo de operación (descubrimiento o GET).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_template_nodes', to='oids.oid'),
        ),
    ]
