# Generated by Django 4.2.16 on 2025-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_jobs', '0011_simplify_template_node_use_oid_directly'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='Última ejecución de este nodo', null=True),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Próxima ejecución para este nodo específico del workflow', null=True),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='default_priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy Alta'), (2, 'Alta'), (3, 'Media'), (4, 'Baja'), (5, 'Muy Baja')], default=3),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy Alta'), (2, 'Alta'), (3, 'Media'), (4, 'Baja'), (5, 'Muy Baja')], db_index=True, default=3),
        ),
        migrations.AlterField(
            model_name='workflowtemplatenode',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy Alta'), (2, 'Alta'), (3, 'Media'), (4, 'Baja'), (5, 'Muy Baja')], default=3),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['next_run_at'], name='snmp_workfl_next_ru_3c7b89_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'enabled', 'next_run_at'], name='snmp_workfl_workflo_39ffa6_idx'),
        ),
    ]
