# Generated by Django 4.2.16 on 2025-11-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0008_alter_oid_marca_alter_oid_modelo'),
        ('snmp_jobs', '0014_add_chain_node_fields_to_template_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='oid',
            field=models.ForeignKey(blank=True, db_column='oid_id', help_text='OID SNMP para ejecutar este nodo (obligatorio para ejecución)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_nodes', to='oids.oid'),
        ),
    ]
