# Generated by Django 5.2.5 on 2025-10-13 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snmp_formulas', '0004_alter_indexformula_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador de esta configuración', max_length=100, unique=True, verbose_name='Nombre de Configuración')),
                ('zabbix_url', models.URLField(help_text='URL completa de la API de Zabbix (ej: http://zabbix.example.com/api_jsonrpc.php)', max_length=255, verbose_name='URL Zabbix API')),
                ('zabbix_token', models.CharField(help_text='Token de autenticación de Zabbix (se guardará de forma segura)', max_length=255, verbose_name='Token de Autenticación')),
                ('item_key', models.CharField(default='port.descover.walk', help_text='Clave del item master en Zabbix que contiene el SNMP walk completo', max_length=100, verbose_name='Clave del Item Master')),
                ('activa', models.BooleanField(default=True, help_text='Solo puede haber una configuración activa a la vez', verbose_name='Configuración Activa')),
                ('timeout', models.IntegerField(default=30, help_text='Tiempo máximo de espera para peticiones a Zabbix', verbose_name='Timeout (segundos)')),
                ('verificar_ssl', models.BooleanField(default=True, help_text='Verificar certificados SSL en las peticiones', verbose_name='Verificar SSL')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de esta configuración', null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('formula_snmp', models.ForeignKey(help_text='Fórmula SNMP para calcular slot/port desde índices SNMP de Zabbix', on_delete=django.db.models.deletion.PROTECT, related_name='zabbix_configs', to='snmp_formulas.indexformula', verbose_name='Fórmula SNMP')),
            ],
            options={
                'verbose_name': 'Configuración de Zabbix',
                'verbose_name_plural': 'Configuraciones de Zabbix',
                'db_table': 'zabbix_configuration',
                'ordering': ['-activa', '-updated_at'],
                'indexes': [models.Index(fields=['activa'], name='zabbix_conf_activa_67962a_idx'), models.Index(fields=['nombre'], name='zabbix_conf_nombre_6271eb_idx')],
            },
        ),
    ]
