# Generated by Django 5.2.5 on 2025-10-13 16:35

from django.db import migrations


def create_default_config(apps, schema_editor):
    """
    Crea una configuración por defecto de Zabbix
    """
    ZabbixConfiguration = apps.get_model('zabbix_config', 'ZabbixConfiguration')
    IndexFormula = apps.get_model('snmp_formulas', 'IndexFormula')
    Brand = apps.get_model('brands', 'Brand')
    
    # Buscar fórmula Huawei genérica como default
    try:
        huawei = Brand.objects.get(nombre='Huawei')
        formula = IndexFormula.objects.filter(
            marca=huawei,
            modelo__isnull=True,
            activo=True
        ).first()
        
        if not formula:
            # Si no hay fórmula Huawei, buscar la primera fórmula universal
            formula = IndexFormula.objects.filter(
                marca__isnull=True,
                modelo__isnull=True,
                activo=True
            ).first()
        
        if formula:
            # Crear configuración por defecto
            ZabbixConfiguration.objects.get_or_create(
                nombre='Configuración Principal',
                defaults={
                    'zabbix_url': 'http://localhost/zabbix/api_jsonrpc.php',
                    'zabbix_token': 'INSERTAR_TOKEN_AQUI',
                    'item_key': 'port.descover.walk',
                    'formula_snmp': formula,
                    'activa': True,
                    'timeout': 30,
                    'verificar_ssl': True,
                    'descripcion': 'Configuración principal de Zabbix. Actualiza la URL, token y fórmula según tu entorno.'
                }
            )
            print("✅ Configuración por defecto de Zabbix creada")
        else:
            print("⚠️ No se encontró fórmula SNMP para crear configuración por defecto")
            
    except Brand.DoesNotExist:
        print("⚠️ Marca Huawei no encontrada. Configuración Zabbix no creada automáticamente.")


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_config', '0001_initial'),
        ('snmp_formulas', '0004_alter_indexformula_marca_and_more'),  # Asegurar que las fórmulas existan
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_config, reverse_code=migrations.RunPython.noop),
    ]
