# Generated by Django 4.2.16 on 2025-10-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_config', '0002_create_default_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabbixconfiguration',
            name='formula_snmp',
        ),
    ]
