# Generated by Django 5.2.5 on 2025-09-24 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'SD-ANILLOS-SD 1-45'", max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, to='hosts.olt')),
            ],
            options={
                'verbose_name': 'ODF (Marco de Distribución Óptica)',
                'verbose_name_plural': 'ODFs (Marcos de Distribución Óptica)',
                'db_table': 'odf',
                'ordering': ['olt', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ODFHilos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(help_text='Número de slot en la OLT')),
                ('port', models.IntegerField(help_text='Número de puerto en el slot')),
                ('hilo_numero', models.IntegerField(help_text='Número físico del hilo hacia la NAP')),
                ('vlan', models.IntegerField(help_text='VLAN de conexión configurada')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('enabled', 'Habilitado'), ('disabled', 'Deshabilitado')], default='enabled', help_text='Estado controlado por Zabbix', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('odf', models.ForeignKey(db_column='odf_id', on_delete=django.db.models.deletion.CASCADE, to='odf_management.odf')),
            ],
            options={
                'verbose_name': 'Hilo ODF',
                'verbose_name_plural': 'Hilos ODF',
                'db_table': 'odf_hilos',
                'ordering': ['odf', 'slot', 'port', 'hilo_numero'],
            },
        ),
        migrations.AddIndex(
            model_name='odf',
            index=models.Index(fields=['olt'], name='odf_olt_id_1b088f_idx'),
        ),
        migrations.AddIndex(
            model_name='odf',
            index=models.Index(fields=['nombre'], name='odf_nombre_da2f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='odfhilos',
            index=models.Index(fields=['odf'], name='odf_hilos_odf_id_ff8430_idx'),
        ),
        migrations.AddIndex(
            model_name='odfhilos',
            index=models.Index(fields=['slot', 'port'], name='odf_hilos_slot_3fab1c_idx'),
        ),
        migrations.AddIndex(
            model_name='odfhilos',
            index=models.Index(fields=['vlan'], name='odf_hilos_vlan_1eea71_idx'),
        ),
        migrations.AddIndex(
            model_name='odfhilos',
            index=models.Index(fields=['estado'], name='odf_hilos_estado_afb91a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='odfhilos',
            unique_together={('odf', 'slot', 'port', 'hilo_numero')},
        ),
    ]
