# Generated by Django 5.2.5 on 2025-09-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        ('odf_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odfhilos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='odfhilos',
            name='descripcion_manual',
            field=models.TextField(blank=True, help_text='Descripción manual del hilo/troncal', null=True),
        ),
        migrations.AlterField(
            model_name='odfhilos',
            name='estado',
            field=models.CharField(choices=[('enabled', 'Habilitado'), ('disabled', 'Deshabilitado')], default='enabled', help_text='Estado del hilo', max_length=20),
        ),
        migrations.CreateModel(
            name='ZabbixPortData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snmp_index', models.CharField(help_text='Índice SNMP de la interfaz', max_length=50)),
                ('slot', models.IntegerField(help_text='Slot calculado desde SNMP index')),
                ('port', models.IntegerField(help_text='Port calculado desde SNMP index')),
                ('descripcion_zabbix', models.TextField(blank=True, help_text='Descripción cruda desde Zabbix', null=True)),
                ('interface_name', models.CharField(blank=True, help_text='Nombre de interfaz (ej: GPON 0/4/15)', max_length=100, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, to='hosts.olt')),
            ],
            options={
                'verbose_name': 'Datos de Puerto Zabbix',
                'verbose_name_plural': 'Datos de Puertos Zabbix',
                'db_table': 'zabbix_port_data',
                'ordering': ['olt', 'slot', 'port'],
            },
        ),
        migrations.AddField(
            model_name='odfhilos',
            name='zabbix_port',
            field=models.ForeignKey(blank=True, help_text='Puerto asociado desde datos de Zabbix (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='odf_management.zabbixportdata'),
        ),
        migrations.AddIndex(
            model_name='zabbixportdata',
            index=models.Index(fields=['olt', 'slot', 'port'], name='zabbix_port_olt_id_aae011_idx'),
        ),
        migrations.AddIndex(
            model_name='zabbixportdata',
            index=models.Index(fields=['snmp_index'], name='zabbix_port_snmp_in_7b1214_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zabbixportdata',
            unique_together={('olt', 'snmp_index')},
        ),
    ]
