# Generated by Django 5.2.5 on 2025-09-24 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        ('odf_management', '0002_remove_odfhilos_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixCollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para esta programación', max_length=100)),
                ('intervalo_minutos', models.IntegerField(choices=[(5, 'Cada 5 minutos (:05, :10, :15, :20...)'), (10, 'Cada 10 minutos (:10, :20, :30, :40...)'), (15, 'Cada 15 minutos (:15, :30, :45, :00...)'), (20, 'Cada 20 minutos (:20, :40, :00...)'), (30, 'Cada 30 minutos (:30, :00...)'), (60, 'Cada 60 minutos (cada hora)')], default=15, help_text='Intervalo de recolección en minutos')),
                ('habilitado', models.BooleanField(default=True, help_text='Si está habilitada la programación')),
                ('proxima_ejecucion', models.DateTimeField(blank=True, help_text='Próxima ejecución programada', null=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, help_text='Última ejecución completada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programación de Recolección Zabbix',
                'verbose_name_plural': 'Programaciones de Recolección Zabbix',
                'db_table': 'zabbix_collection_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZabbixCollectionOLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True, help_text='Si esta OLT está habilitada para recolección')),
                ('ultima_recoleccion', models.DateTimeField(blank=True, help_text='Última vez que se recolectaron datos de esta OLT', null=True)),
                ('ultimo_estado', models.CharField(choices=[('success', 'Exitoso'), ('error', 'Error'), ('pending', 'Pendiente')], default='pending', help_text='Estado de la última recolección', max_length=20)),
                ('ultimo_error', models.TextField(blank=True, help_text='Último error encontrado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.olt', verbose_name='OLT')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odf_management.zabbixcollectionschedule', verbose_name='Programación')),
            ],
            options={
                'verbose_name': 'OLT en Programación',
                'verbose_name_plural': 'OLTs en Programación',
                'db_table': 'zabbix_collection_olt',
                'ordering': ['schedule', 'olt'],
                'unique_together': {('schedule', 'olt')},
            },
        ),
    ]
