# Generated by Django 5.2.5 on 2025-09-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        ('odf_management', '0003_zabbixcollectionschedule_zabbixcollectionolt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odf',
            options={'ordering': ['olt', 'nombre_troncal'], 'verbose_name': 'ODF (Marco de Distribución Óptica)', 'verbose_name_plural': 'ODFs (Marcos de Distribución Óptica)'},
        ),
        migrations.RemoveIndex(
            model_name='odf',
            name='odf_nombre_da2f0d_idx',
        ),
        migrations.RemoveField(
            model_name='odf',
            name='nombre',
        ),
        migrations.AddField(
            model_name='odf',
            name='nombre_troncal',
            field=models.CharField(default=1, help_text='Nombre único de la troncal por OLT (ej: CHOSICA-SANTA EULALIA 2 T-24)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odfhilos',
            name='en_zabbix',
            field=models.BooleanField(default=False, help_text='Si actualmente aparece en los datos de Zabbix'),
        ),
        migrations.AddField(
            model_name='odfhilos',
            name='origen',
            field=models.CharField(choices=[('zabbix', 'Desde Zabbix'), ('manual', 'Manual')], default='manual', help_text='Indica si los datos provienen de Zabbix o son manuales', max_length=20),
        ),
        migrations.AlterField(
            model_name='odfhilos',
            name='estado',
            field=models.CharField(choices=[('enabled', 'Habilitado (En Zabbix)'), ('disabled', 'Deshabilitado (No en Zabbix)')], default='disabled', help_text="Solo 'enabled' si aparece actualmente en Zabbix", max_length=20),
        ),
        migrations.AddIndex(
            model_name='odf',
            index=models.Index(fields=['nombre_troncal'], name='odf_nombre__4d3263_idx'),
        ),
        migrations.AddIndex(
            model_name='odfhilos',
            index=models.Index(fields=['origen'], name='odf_hilos_origen_f41dde_idx'),
        ),
        migrations.AddIndex(
            model_name='odfhilos',
            index=models.Index(fields=['en_zabbix'], name='odf_hilos_en_zabb_04401a_idx'),
        ),
        migrations.AddConstraint(
            model_name='odf',
            constraint=models.UniqueConstraint(fields=('olt', 'nombre_troncal'), name='unique_troncal_per_olt'),
        ),
    ]
