# Generated by Django 5.2.5 on 2025-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        ('odf_management', '0004_alter_odf_options_remove_odf_odf_nombre_da2f0d_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odf',
            options={'ordering': ['olt', 'numero_odf', 'nombre_troncal'], 'verbose_name': 'ODF (Marco de Distribución Óptica)', 'verbose_name_plural': 'ODFs (Marcos de Distribución Óptica)'},
        ),
        migrations.AddField(
            model_name='odf',
            name='numero_odf',
            field=models.IntegerField(default=1, help_text='Número del ODF (ej: 1, 2, 3...)'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='odf',
            index=models.Index(fields=['numero_odf'], name='odf_numero__66f374_idx'),
        ),
        migrations.AddIndex(
            model_name='odf',
            index=models.Index(fields=['olt', 'numero_odf'], name='odf_olt_id_dbce87_idx'),
        ),
    ]
