# Generated by Django 5.2.5 on 2025-09-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odf_management', '0005_alter_odf_options_odf_numero_odf_and_more'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odfhilos',
            name='fecha_habilitacion',
            field=models.DateField(blank=True, help_text='Fecha en la que se habilitó el hilo (obligatorio, manual)', null=True),
        ),
        migrations.AddField(
            model_name='odfhilos',
            name='personal_noc',
            field=models.ForeignKey(blank=True, help_text='Personal NOC responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos_noc', to='personal.personal'),
        ),
        migrations.AddField(
            model_name='odfhilos',
            name='personal_proyectos',
            field=models.ForeignKey(blank=True, help_text='Personal de Proyectos responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos_proyectos', to='personal.personal'),
        ),
        migrations.AddField(
            model_name='odfhilos',
            name='tecnico_habilitador',
            field=models.ForeignKey(blank=True, help_text='Técnico que habilitó el hilo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilos_habilitados', to='personal.personal'),
        ),
    ]
