# Generated by Django 5.2.5 on 2025-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odf_management', '0006_odfhilos_fecha_habilitacion_odfhilos_personal_noc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odfhilos',
            name='fecha_habilitacion',
            field=models.DateField(default='2024-01-01', help_text='Fecha en la que se habilitó el hilo (obligatorio, manual)'),
        ),
    ]
