# Generated by Django 5.2.5 on 2025-09-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odf_management', '0007_alter_odfhilos_fecha_habilitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixportdata',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Si el puerto está disponible en la última recolección de Zabbix'),
        ),
    ]
