# Generated by Django 5.2.5 on 2025-09-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odf_management', '0009_optimize_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='odfhilos',
            name='operativo_noc',
            field=models.BooleanField(default=False, help_text='Si el hilo está operativo según NOC (configuración manual)'),
        ),
        migrations.AddField(
            model_name='zabbixportdata',
            name='operativo_noc',
            field=models.BooleanField(default=False, help_text='Si el puerto está operativo según NOC (configuración manual)'),
        ),
    ]
