# Generated by Django 5.2.5 on 2025-09-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odf_management', '0010_odfhilos_operativo_noc_zabbixportdata_operativo_noc'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixportdata',
            name='estado_administrativo',
            field=models.IntegerField(blank=True, choices=[(1, 'ACTIVO'), (2, 'INACTIVO')], help_text='Estado administrativo del puerto desde OID .1.3.6.1.2.1.2.2.1.7 (1=ACTIVO, 2=INACTIVO)', null=True),
        ),
    ]
