# Generated by Django 5.2.5 on 2025-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odf_management', '0011_add_estado_administrativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='odfhilos',
            name='hora_habilitacion',
            field=models.TimeField(blank=True, help_text='Hora en la que se habilitó el hilo (opcional, manual)', null=True),
        ),
    ]
