# Generated by Django 5.2.5 on 2025-08-30 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('habilitar_olt', models.BooleanField(default=True, help_text='Indica si la OLT está habilitada para consultas SNMP')),
                ('comunidad', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'verbose_name': 'OLT',
                'verbose_name_plural': 'OLTs',
                'db_table': 'olt',
                'managed': True,
            },
        ),
    ]
