# Generated by Django 5.2.5 on 2025-10-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo específico de la OLT (ej: MA5800, C320, etc.). Opcional.', max_length=100, null=True, verbose_name='Modelo'),
        ),
    ]
