# Generated by Django 5.2.5 on 2025-10-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_olt_modelo'),
        ('olt_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olt',
            name='modelo',
            field=models.ForeignKey(blank=True, db_column='modelo_id', help_text='Modelo específico de la OLT. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='olt_models.oltmodel', verbose_name='Modelo'),
        ),
    ]
