# Generated by Django 4.2.16 on 2025-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_add_soft_delete_to_olt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olt',
            options={'managed': True, 'ordering': ['abreviatura'], 'verbose_name': 'OLT', 'verbose_name_plural': 'OLTs'},
        ),
        migrations.AlterField(
            model_name='olt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),
        ),
    ]
