# Generated by Django 5.2.5 on 2025-10-03 20:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCelery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la configuración Celery', max_length=100, unique=True)),
                ('cola', models.CharField(help_text='Nombre de la cola de Celery', max_length=50)),
                ('concurrencia', models.PositiveIntegerField(default=1, help_text='Número de workers concurrentes (1-50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('timeout_tarea', models.PositiveIntegerField(default=300, help_text='Timeout de tareas en segundos (30-3600)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3600)])),
                ('reintentos_tarea', models.PositiveSmallIntegerField(default=0, help_text='Número de reintentos automáticos (0-10)', validators=[django.core.validators.MaxValueValidator(10)])),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se aplica a la cola')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Celery',
                'verbose_name_plural': 'Configuraciones Celery',
                'db_table': 'configuracion_celery',
                'ordering': ['cola', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la configuración SNMP', max_length=100, unique=True)),
                ('timeout', models.PositiveIntegerField(default=5, help_text='Timeout en segundos (1-300)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('reintentos', models.PositiveSmallIntegerField(default=0, help_text='Número de reintentos (0-10)', validators=[django.core.validators.MaxValueValidator(10)])),
                ('comunidad', models.CharField(default='public', help_text='Comunidad SNMP por defecto', max_length=50)),
                ('version', models.CharField(choices=[('1', 'SNMPv1'), ('2c', 'SNMPv2c'), ('3', 'SNMPv3')], default='2c', help_text='Versión de SNMP', max_length=10)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se aplica a todas las operaciones SNMP')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SNMP',
                'verbose_name_plural': 'Configuraciones SNMP',
                'db_table': 'configuracion_snmp',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador de la configuración', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de qué hace esta configuración')),
                ('valor', models.TextField(help_text='Valor de la configuración (puede ser texto, número, JSON, etc.)')),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Entero'), ('float', 'Número Decimal'), ('boolean', 'Verdadero/Falso'), ('json', 'JSON'), ('url', 'URL'), ('email', 'Email')], default='string', help_text='Tipo de dato del valor', max_length=20)),
                ('categoria', models.CharField(choices=[('snmp', 'SNMP'), ('celery', 'Celery'), ('redis', 'Redis'), ('database', 'Base de Datos'), ('logging', 'Logging'), ('security', 'Seguridad'), ('performance', 'Rendimiento'), ('general', 'General')], default='general', help_text='Categoría de la configuración', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, la configuración se aplica')),
                ('solo_lectura', models.BooleanField(default=False, help_text='Si es solo lectura, no se puede modificar desde el admin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó por última vez esta configuración', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
