# Generated by Django 5.2.5 on 2025-10-07 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_avanzada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsnmp',
            options={'ordering': ['tipo_operacion', 'nombre'], 'verbose_name': 'Configuración SNMP', 'verbose_name_plural': 'Configuraciones SNMP'},
        ),
        migrations.AddField(
            model_name='configuracionsnmp',
            name='delay_entre_reintentos',
            field=models.PositiveSmallIntegerField(default=5, help_text='Segundos entre reintentos (solo para GET)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='configuracionsnmp',
            name='max_consultas_snmp_simultaneas',
            field=models.PositiveSmallIntegerField(default=5, help_text='Máximo de consultas SNMP simultáneas por poller (Semaphore)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='configuracionsnmp',
            name='max_pollers_por_olt',
            field=models.PositiveSmallIntegerField(default=10, help_text='Máximo de pollers concurrentes por OLT (solo para GET)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='configuracionsnmp',
            name='max_reintentos_individuales',
            field=models.PositiveSmallIntegerField(default=2, help_text='Reintentos para ONUs individuales (solo para GET)', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='configuracionsnmp',
            name='tamano_lote_inicial',
            field=models.PositiveIntegerField(default=200, help_text='Tamaño del lote inicial de ONUs (solo para GET)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='configuracionsnmp',
            name='tamano_subdivision',
            field=models.PositiveSmallIntegerField(default=50, help_text='Tamaño al subdividir lotes con errores (solo para GET)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='configuracionsnmp',
            name='tipo_operacion',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento (SNMP Walk)'), ('get', 'GET (Consultas Individuales)'), ('bulk', 'BULK (Consultas Masivas)'), ('table', 'TABLE (Tablas)'), ('general', 'General (Todas las operaciones)')], default='general', help_text='Tipo de operación SNMP a la que se aplica', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracionsnmp',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está activo, se aplica a las operaciones del tipo especificado'),
        ),
        migrations.AlterField(
            model_name='configuracionsnmp',
            name='reintentos',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de reintentos SNMP (0-10)', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
