# Generated by Django 4.2.16 on 2025-11-17 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_avanzada', '0002_alter_configuracionsnmp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='modo_prueba',
            field=models.BooleanField(default=False, help_text='MODO PRUEBA: Si está activo, TODAS las ejecuciones SNMP se simulan sin realizar consultas reales. Los tiempos de ejecución son aleatorios (milisegundos a 3 minutos).'),
        ),
        migrations.AlterField(
            model_name='configuracionsnmp',
            name='max_consultas_snmp_simultaneas',
            field=models.PositiveSmallIntegerField(default=10, help_text='Máximo de consultas SNMP simultáneas por poller (Semaphore)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
