# Generated by Django 4.2.16 on 2025-11-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_avanzada', '0003_add_modo_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionCelery',
        ),
        migrations.AlterField(
            model_name='configuracionsnmp',
            name='tipo_operacion',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento (SNMP Walk)'), ('get', 'GET (Consultas Individuales)'), ('walk', 'WALK (Recorrido de árbol SNMP)'), ('bulk', 'BULK (Consultas Masivas)'), ('table', 'TABLE (Tablas)'), ('general', 'General (Todas las operaciones)')], default='general', help_text='Tipo de operación SNMP a la que se aplica', max_length=20),
        ),
    ]
