"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import configparser

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Leer configuración desde dos archivos separados
# - backend.conf: Configuración del backend (BD, API, sistema)
# - https.conf: Configuración HTTPS (opcional)
backend_config_path = '/etc/facho_deluxe_2/backend.conf'
https_config_path = '/etc/facho_deluxe_2/https.conf'

# Verificar archivo de backend (obligatorio)
if not os.path.exists(backend_config_path):
    raise FileNotFoundError(
        f"Archivo de configuración no encontrado: {backend_config_path}\n"
        f"Ejecuta el script de despliegue: sudo ./deploy_backend.sh\n"
        f"O crea manualmente el archivo de configuración."
    )

if not os.access(backend_config_path, os.R_OK):
    raise PermissionError(
        f"No se puede leer el archivo de configuración: {backend_config_path}\n"
        f"Verifica los permisos del archivo. Debe ser legible por el usuario que ejecuta Django."
    )

# Leer configuración del backend
backend_config = configparser.ConfigParser()
backend_config.read(backend_config_path)

# Leer configuración HTTPS (opcional)
https_config = configparser.ConfigParser()
if os.path.exists(https_config_path) and os.access(https_config_path, os.R_OK):
    https_config.read(https_config_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vyeue=sj-%&g2l%n8l(9g76mh)=bzac4th384k7!%ly3w=asr9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Obtener IP de la API desde backend.conf
api_ip = backend_config.get('api', 'api_ip', fallback='0.0.0.0')

# Configuración HTTPS desde https.conf (opcional)
protocol = https_config.get('https', 'protocol', fallback='http') if https_config.has_section('https') else 'http'
https_domain = https_config.get('https', 'https_domain', fallback=None) if https_config.has_section('https') else None

# Construir ALLOWED_HOSTS
allowed_hosts_list = [api_ip, 'localhost', '127.0.0.1']
if https_domain:
    allowed_hosts_list.append(https_domain)
if protocol == 'http':
    allowed_hosts_list.append('*')  # Permitir todos en HTTP

ALLOWED_HOSTS = allowed_hosts_list

# Configuración de seguridad HTTPS (si protocol = https)
if protocol == 'https':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = False  # NGINX maneja la redirección

# Configuración CSRF - Orígenes confiables
# Incluir el backend y el frontend
frontend_config_path = '/etc/facho-frontend/frontend.conf'

csrf_trusted_origins = [
    f'https://{api_ip}',  # Backend
    f'http://{api_ip}',   # Backend HTTP (si aplica)
]
if https_domain:
    csrf_trusted_origins.append(f'https://{https_domain}')
    csrf_trusted_origins.append(f'http://{https_domain}')

# Agregar origen del frontend si existe la configuración
if os.path.exists(frontend_config_path) and os.access(frontend_config_path, os.R_OK):
    try:
        frontend_config = configparser.ConfigParser()
        frontend_config.read(frontend_config_path)
        if frontend_config.has_section('frontend'):
            frontend_ip = frontend_config.get('frontend', 'frontend_ip', fallback=None)
            frontend_port = frontend_config.get('frontend', 'frontend_port', fallback=None)
            frontend_protocol = frontend_config.get('frontend', 'protocol', fallback='https')
            if frontend_ip and frontend_port:
                frontend_url = f"{frontend_protocol}://{frontend_ip}:{frontend_port}"
                if frontend_url not in csrf_trusted_origins:
                    csrf_trusted_origins.append(frontend_url)
    except Exception:
        pass  # Si hay error leyendo la configuración, usar solo los valores por defecto

# Si no se encontró configuración del frontend, agregar puerto 8443 por defecto si es la misma IP
if api_ip == '10.80.80.229':
    default_frontend = f'https://{api_ip}:8443'
    if default_frontend not in csrf_trusted_origins:
        csrf_trusted_origins.append(default_frontend)

CSRF_TRUSTED_ORIGINS = csrf_trusted_origins


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # REST Framework
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    # Apps del proyecto
    "hosts",
    "snmp_jobs",
    "executions",
    "execution_utils",  # Utilidades de ejecución (callbacks, eventos, logging)
    "discovery",
    "brands",
    "oids",
    "odf_management",
    "personal",
    "configuracion_avanzada",
    "snmp_get",
    "snmp_formulas",
    "olt_models",
    "zabbix_config",
    "zabbix_pollers",  # Sistema de Pollers Zabbix (reemplaza coordinador)
    "api",  # App de la REST API
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS para REST API
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': backend_config.get('database', 'name', fallback='dbname'),
        'USER': backend_config.get('database', 'user', fallback='dbuser'),
        'PASSWORD': backend_config.get('database', 'password', fallback='change_me_in_config_ini'),
        'HOST': backend_config.get('database', 'host', fallback='localhost'),
        'PORT': backend_config.get('database', 'port', fallback='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Configuración de colas específicas
CELERY_TASK_ROUTES = {
    'snmp_jobs.tasks.discovery_main_task': {'queue': 'discovery_main'},
    'snmp_jobs.tasks.discovery_retry_task': {'queue': 'discovery_retry'},
    'snmp_jobs.tasks.discovery_manual_task': {'queue': 'discovery_manual'},  # Máxima prioridad
    'snmp_jobs.tasks.dispatcher_check_and_enqueue': {'queue': 'discovery_main'},
    'snmp_jobs.tasks.cleanup_old_executions_task': {'queue': 'cleanup'},
    'snmp_jobs.tasks.delete_history_records': {'queue': 'background_deletes'},
    # Tareas de ODF Management
    'odf_management.tasks.sync_single_olt_ports': {'queue': 'odf_sync'},
    'odf_management.tasks.sync_scheduled_olts': {'queue': 'odf_sync'},
    'odf_management.tasks.cleanup_old_sync_logs': {'queue': 'cleanup'},
    # Tareas de sincronización masiva batch
    'odf_management.tasks.sync_all_odf_hilos': {'queue': 'odf_sync'},
    'odf_management.tasks.sync_odf_hilos_for_olt': {'queue': 'odf_sync'},
    # Tareas de SNMP GET con pollers
    'snmp_get.tasks.get_main_task': {'queue': 'get_main'},
    'snmp_get.tasks.get_retry_task': {'queue': 'get_retry'},
    'snmp_get.tasks.get_poller_task': {'queue': 'get_poller'},
    'snmp_get.tasks.get_manual_task': {'queue': 'get_manual'},
    # Tareas de limpieza GET
    'snmp_get.cleanup_tasks.cleanup_interrupted_executions': {'queue': 'cleanup'},
    'snmp_get.cleanup_tasks.cancel_pending_executions_for_disabled_jobs': {'queue': 'cleanup'},
    # ✅ ELIMINADO: Tareas del coordinador antiguo ya no existen (modelos CoordinatorLog y CoordinatorEvent eliminados)
}

# Configuración de workers
CELERY_WORKER_CONCURRENCY = 20  # Para cola principal

# Configuración de reintentos
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Configuración de timeouts
CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutos
CELERY_TASK_TIME_LIMIT = 600       # 10 minutos

# Configuración de beat (scheduler)
CELERY_BEAT_SCHEDULE = {
    # ✅ ELIMINADO: dispatcher-check-and-enqueue y coordinator-loop ya no existen (reemplazados por zabbix-scheduler)
    'zabbix-scheduler': {
        'task': 'zabbix_pollers.tasks.zabbix_scheduler_loop_task',
        'schedule': 1.0,  # Cada 1 segundo - loop del scheduler Zabbix
        'options': {
            'queue': 'zabbix_scheduler',
            'expires': 0.5,  # Expira antes del siguiente
        }
    },
    # ✅ ELIMINADO: check-delivery ya no existe (el sistema de pollers Zabbix maneja esto directamente)
    # ✅ ELIMINADO: Tareas de cleanup de coordinator logs ya no existen (modelos CoordinatorLog y CoordinatorEvent eliminados)
    'odf-scheduled-collection': {
        'task': 'odf_management.tasks.sync_scheduled_olts',
        'schedule': 60.0,  # Cada minuto - verifica programaciones de ODF
    },
    'odf-cleanup-old-logs': {
        'task': 'odf_management.tasks.cleanup_old_sync_logs',
        'schedule': 86400.0,  # Una vez al día - limpia logs antiguos
    },
    'sync-odf-hilos-every-5min': {
        'task': 'odf_management.tasks.sync_all_odf_hilos',
        'schedule': 300.0,  # Cada 5 minutos - sincronización masiva batch
    },
    'cleanup-interrupted-get-executions': {
        'task': 'snmp_get.cleanup_tasks.cleanup_interrupted_executions',
        'schedule': 1800.0,  # Cada 30 minutos - limpiar ejecuciones GET interrumpidas
    },
    # ✅ DESACTIVADO: sync-pending-executions-with-celery
    # Los errores de EasySNMP se manejan automáticamente en el bloque except
    # No se necesita un proceso periódico que descarte ejecuciones
    # 'sync-pending-executions-with-celery': {
    #     'task': 'snmp_jobs.cleanup_tasks.sync_pending_executions_with_celery',
    #     'schedule': 300.0,  # Cada 5 minutos - sincronizar ejecuciones PENDING con estado real de Celery
    # },
}

# Configuración de timeouts para tareas de descubrimiento
CELERY_TASK_SOFT_TIME_LIMIT = 180  # 3 minutos soft limit
CELERY_TASK_TIME_LIMIT = 200  # 3.5 minutos hard limit

# Configuración de reintentos
MAX_RETRIES = 3
RETRY_DELAY_SECONDS = 30  # segundos entre reintentos

# Configuración SNMP
SNMP_TIMEOUT = 10  # segundos (reducido de 30)
SNMP_RETRIES = 0  # solo 1 reintento (reducido de 3)
SNMP_COMMUNITY = 'public'

# Configuración de descubrimiento
MAX_CONSECUTIVE_FAILURES = 3
MAX_TOTAL_FAILURES = 5
RETRY_DELAYS = [60, 300, 600]  # segundos

# Configuración de monitoreo
TASK_CHECK_INTERVAL = 60  # segundos
OLT_HEALTH_CHECK_INTERVAL = 300  # segundos

# NOTA: La configuración de Zabbix se gestiona desde Django Admin
# Ver modelo: zabbix_config.models.ZabbixConfiguration
# Uso: ZabbixConfiguration.get_active_config()

# ============================================================================
# CONFIGURACIÓN DE REST FRAMEWORK
# ============================================================================

REST_FRAMEWORK = {
    # Esquema de API (para documentación automática)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Autenticación - API Key personalizada (x-api-key header)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.APIKeyAuthentication',  # Autenticación personalizada con x-api-key
        # SessionAuthentication y BasicAuthentication deshabilitados para producción
        # Solo se permite autenticación por API Key
    ],
    
    # Permisos - Requiere autenticación por defecto
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Paginación
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    
    # Filtros
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    
    # Formato de respuesta - SOLO JSON para producción
    # BrowsableAPIRenderer deshabilitado para mayor seguridad
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        # BrowsableAPIRenderer deshabilitado en producción
    ],
    
    # Límite de solicitudes (throttling)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'monitoring': '300/minute',  # Para endpoints de monitoreo (pollers, stats, queue)
        'high_frequency_monitoring': '600/minute',  # Para monitoreo de alta frecuencia
    },
    
    # Formato de fecha/hora
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}

# Configuración de drf-spectacular (documentación de API)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Facho Deluxe v2 API',
    'DESCRIPTION': 'API REST para gestión de SNMP, ONUs, ODF y Zabbix',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1',
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Desarrollo'},
        {'url': 'http://127.0.0.1:8000', 'description': 'Local'},
    ],
    'TAGS': [
        {'name': 'Hosts', 'description': 'Gestión de hosts OLT'},
        {'name': 'Discovery', 'description': 'Descubrimiento de ONUs'},
        {'name': 'SNMP Jobs', 'description': 'Trabajos SNMP programados'},
        {'name': 'Executions', 'description': 'Ejecuciones y monitoreo'},
        {'name': 'ODF', 'description': 'Gestión de ODF'},
        {'name': 'Formulas', 'description': 'Fórmulas SNMP'},
        {'name': 'Auth', 'description': 'Autenticación y permisos'},
    ],
}

# Configuración de CORS (Cross-Origin Resource Sharing)
# Leer configuración del frontend si existe (frontend_config_path ya definido arriba)
frontend_origins = [
    'http://localhost:3000',  # React/Vite frontend (desarrollo)
    'http://127.0.0.1:3000',
    'http://localhost:4200',  # Angular (opcional)
    'http://localhost:8080',  # Vue.js (opcional)
    'http://127.0.0.1:4200',
    'http://127.0.0.1:8080',
]

# Agregar origen del frontend en producción si existe la configuración
if os.path.exists(frontend_config_path) and os.access(frontend_config_path, os.R_OK):
    try:
        frontend_config = configparser.ConfigParser()
        frontend_config.read(frontend_config_path)
        if frontend_config.has_section('frontend'):
            frontend_ip = frontend_config.get('frontend', 'frontend_ip', fallback=None)
            frontend_port = frontend_config.get('frontend', 'frontend_port', fallback=None)
            frontend_protocol = frontend_config.get('frontend', 'protocol', fallback='https')
            if frontend_ip and frontend_port:
                frontend_url = f"{frontend_protocol}://{frontend_ip}:{frontend_port}"
                if frontend_url not in frontend_origins:
                    frontend_origins.append(frontend_url)
    except Exception:
        pass  # Si hay error leyendo la configuración, usar solo los valores por defecto

CORS_ALLOWED_ORIGINS = frontend_origins

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',  # Header para autenticación personalizada
]

# Configuración de sincronización ODF
ODF_SYNC_INTERVAL = int(os.getenv('ODF_SYNC_INTERVAL', '300'))  # 5 minutos por defecto
ODF_HEALTH_CHECK_INTERVAL = int(os.getenv('ODF_HEALTH_CHECK_INTERVAL', '600'))  # 10 minutos


