# Generated by Django 5.2.5 on 2025-09-25 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('proyectos', 'Proyectos'), ('noc', 'NOC (Network Operations Center)'), ('tecnico', 'Técnico de Campo'), ('supervision', 'Supervisión'), ('gerencia', 'Gerencia')], help_text='Código único del área', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del área', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del área', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Si el área está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área de Trabajo',
                'verbose_name_plural': 'Áreas de Trabajo',
                'db_table': 'personal_area',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelPrivilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Básico - Solo lectura'), (2, 'Operador - Lectura y escritura limitada'), (3, 'Supervisor - Gestión completa de su área'), (4, 'Administrador - Gestión completa del sistema'), (5, 'Super Admin - Acceso total')], help_text='Nivel numérico de privilegio (1-5)', unique=True)),
                ('nombre', models.CharField(help_text='Nombre del nivel de privilegio', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción detallada de los permisos')),
                ('permisos_odf', models.JSONField(default=dict, help_text='Permisos específicos para gestión de ODFs')),
                ('permisos_hilos', models.JSONField(default=dict, help_text='Permisos específicos para gestión de hilos')),
                ('activo', models.BooleanField(default=True, help_text='Si el nivel está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel de Privilegio',
                'verbose_name_plural': 'Niveles de Privilegio',
                'db_table': 'personal_nivel_privilegio',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres completos', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos completos', max_length=100)),
                ('documento_identidad', models.CharField(help_text='Número de documento de identidad', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='Correo electrónico corporativo', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono', max_length=20, null=True)),
                ('codigo_empleado', models.CharField(help_text='Código único del empleado', max_length=20, unique=True)),
                ('cargo', models.CharField(help_text='Cargo o posición', max_length=100)),
                ('fecha_ingreso', models.DateField(help_text='Fecha de ingreso a la empresa')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', help_text='Estado actual del personal', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(help_text='Área de trabajo del personal', on_delete=django.db.models.deletion.PROTECT, to='personal.area')),
                ('created_by', models.ForeignKey(blank=True, help_text='Personal que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_creado', to='personal.personal')),
                ('nivel_privilegio', models.ForeignKey(help_text='Nivel de privilegios en el sistema', on_delete=django.db.models.deletion.PROTECT, to='personal.nivelprivilegio')),
                ('usuario_django', models.OneToOneField(blank=True, help_text='Usuario Django asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'personal',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create_odf', 'Creación de ODF'), ('update_odf', 'Modificación de ODF'), ('create_hilo', 'Creación de hilo'), ('update_hilo', 'Modificación de hilo'), ('enable_hilo', 'Habilitación de hilo'), ('disable_hilo', 'Deshabilitación de hilo')], help_text='Tipo de acción realizada', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador', null=True)),
                ('objeto_afectado_tipo', models.CharField(blank=True, help_text='Tipo de objeto afectado (ODF, Hilo, etc.)', max_length=50, null=True)),
                ('objeto_afectado_id', models.IntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(help_text='Personal que realizó la acción', on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historial de Accesos',
                'db_table': 'personal_historial_acceso',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['area'], name='personal_area_id_a76db6_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['nivel_privilegio'], name='personal_nivel_p_716499_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['estado'], name='personal_estado_cdb1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['codigo_empleado'], name='personal_codigo__87bc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['documento_identidad'], name='personal_documen_9f62af_idx'),
        ),
        migrations.AddIndex(
            model_name='historialacceso',
            index=models.Index(fields=['personal'], name='personal_hi_persona_7c00dc_idx'),
        ),
        migrations.AddIndex(
            model_name='historialacceso',
            index=models.Index(fields=['accion'], name='personal_hi_accion_29581e_idx'),
        ),
        migrations.AddIndex(
            model_name='historialacceso',
            index=models.Index(fields=['timestamp'], name='personal_hi_timesta_897404_idx'),
        ),
    ]
