# Generated by Django 5.2.5 on 2025-09-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(help_text='Nombre único del área (ej: Proyectos, NOC, Técnico de Campo)', max_length=100, unique=True),
        ),
    ]
