# Generated by Django 4.2.16 on 2025-10-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0003_alter_olt_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('report', models.JSONField(help_text='Reporte detallado de la violación')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, related_name='quota_violations', to='hosts.olt')),
            ],
            options={
                'verbose_name': 'Violación de Cuota',
                'verbose_name_plural': 'Violaciones de Cuota',
                'db_table': 'quota_violations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['olt', 'created_at'], name='quota_viola_olt_id_0b543e_idx'), models.Index(fields=['severity'], name='quota_viola_severit_cc8ccd_idx'), models.Index(fields=['notified'], name='quota_viola_notifie_4bd083_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotaTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(help_text='Tipo de tarea: discovery, get_descripcion, get_plan, etc.', max_length=50)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('quota_required', models.IntegerField(help_text='Número de ejecuciones requeridas en el período')),
                ('quota_completed', models.IntegerField(default=0, help_text='Ejecuciones completadas exitosamente')),
                ('quota_failed', models.IntegerField(default=0, help_text='Ejecuciones fallidas')),
                ('quota_skipped', models.IntegerField(default=0, help_text='Ejecuciones omitidas por falta de tiempo')),
                ('quota_pending', models.IntegerField(default=0, help_text='Ejecuciones pendientes')),
                ('total_duration_ms', models.BigIntegerField(default=0, help_text='Tiempo total consumido en ms')),
                ('avg_duration_ms', models.IntegerField(blank=True, help_text='Duración promedio en ms', null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('PARTIAL', 'Completado Parcial'), ('FAILED', 'Fallido'), ('QUOTA_NOT_MET', 'Cuota No Cumplida'), ('INTERRUPTED', 'Interrumpido'), ('ADJUSTED', 'Ajustado'), ('AT_RISK', 'En Riesgo')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, related_name='quota_trackers', to='hosts.olt')),
            ],
            options={
                'verbose_name': 'Rastreador de Cuotas',
                'verbose_name_plural': 'Rastreadores de Cuotas',
                'db_table': 'quota_tracker',
                'ordering': ['-period_start', 'olt', 'task_type'],
                'indexes': [models.Index(fields=['olt', 'period_start'], name='quota_track_olt_id_3ddec4_idx'), models.Index(fields=['status'], name='quota_track_status_8f4ae9_idx')],
                'unique_together': {('olt', 'task_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('plan_data', models.JSONField(help_text='Plan completo en formato JSON')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('COMPLETED', 'Completado'), ('SUPERSEDED', 'Reemplazado'), ('ABORTED', 'Abortado')], default='ACTIVE', max_length=20)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('failed_tasks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, related_name='execution_plans', to='hosts.olt')),
            ],
            options={
                'verbose_name': 'Plan de Ejecución',
                'verbose_name_plural': 'Planes de Ejecución',
                'db_table': 'execution_plans',
                'ordering': ['-period_start', 'olt'],
                'indexes': [models.Index(fields=['olt', 'period_start'], name='execution_p_olt_id_ba5b9b_idx'), models.Index(fields=['status'], name='execution_p_status_97b22e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoordinatorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STATE_CHANGE', 'Cambio de Estado'), ('TASK_ADDED', 'Tarea Agregada'), ('TASK_REMOVED', 'Tarea Removida'), ('TASK_MODIFIED', 'Tarea Modificada'), ('PLAN_CREATED', 'Plan Creado'), ('PLAN_ADJUSTED', 'Plan Ajustado'), ('EXECUTION_STARTED', 'Ejecución Iniciada'), ('EXECUTION_COMPLETED', 'Ejecución Completada'), ('EXECUTION_FAILED', 'Ejecución Fallida'), ('EXECUTION_ABORTED', 'Ejecución Abortada'), ('QUOTA_WARNING', 'Advertencia de Cuota'), ('QUOTA_VIOLATION', 'Violación de Cuota'), ('OLT_DISABLED', 'OLT Deshabilitada'), ('OLT_ENABLED', 'OLT Habilitada'), ('SLOW_MODE_ACTIVATED', 'Modo Lento Activado'), ('EMERGENCY_REPLAN', 'Re-planificación de Emergencia'), ('TRIAGE_MODE', 'Modo Triage Activado')], db_index=True, max_length=30)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Detalles adicionales del evento', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('olt', models.ForeignKey(blank=True, db_column='olt_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_logs', to='hosts.olt')),
            ],
            options={
                'verbose_name': 'Log del Coordinador',
                'verbose_name_plural': 'Logs del Coordinador',
                'db_table': 'coordinator_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['olt', 'timestamp'], name='coordinator_olt_id_ca6552_idx'), models.Index(fields=['event_type', 'timestamp'], name='coordinator_event_t_044162_idx'), models.Index(fields=['level', 'timestamp'], name='coordinator_level_365257_idx')],
            },
        ),
    ]
