# Generated by Django 4.2.16 on 2025-11-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_jobs', '0005_snmpjobhost_snmp_job_ho_next_ru_52b7e5_idx'),
        ('executions', '0004_add_interrupted_status'),
        ('hosts', '0003_alter_olt_modelo'),
        ('execution_coordinator', '0002_remove_execution_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENQUEUED', 'Tarea Encolada'), ('REQUEUED', 'Tarea Reencolada'), ('SKIPPED', 'Tarea Omitida'), ('DELAYED', 'Tarea Aplazada'), ('EXECUTION_STARTED', 'Inicio de Ejecución'), ('EXECUTION_COMPLETED', 'Ejecución Completada'), ('EXECUTION_FAILED', 'Ejecución Fallida'), ('EXECUTION_INTERRUPTED', 'Ejecución Interrumpida'), ('AUTO_REPAIR', 'Auto Reparación'), ('SATURATION_WAIT', 'Espera por Saturación'), ('DELIVERY_LOST', 'Entrega Perdida'), ('STATE_UPDATED', 'Estado Actualizado'), ('PLAN_UPDATED', 'Plan Actualizado')], max_length=40)),
                ('decision', models.CharField(blank=True, choices=[('ENQUEUE', 'Encolar'), ('REQUEUE', 'Reencolar'), ('SKIP', 'Omitir'), ('WAIT', 'Esperar'), ('RETRY', 'Programar Reintento'), ('ADJUST', 'Ajustar Plan'), ('ABORT', 'Abortar'), ('COMPLETE', 'Completar')], max_length=20)),
                ('source', models.CharField(choices=[('SCHEDULER', 'Scheduler'), ('QUEUE', 'Cola Diferida'), ('DELIVERY_CHECKER', 'Delivery Checker'), ('AUTO_REPAIR', 'Auto Reparación'), ('ADMIN', 'Acción Manual'), ('SYSTEM', 'Sistema')], default='SCHEDULER', max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, help_text='Contexto adicional en formato JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('execution', models.ForeignKey(blank=True, db_column='execution_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_events', to='executions.execution')),
                ('job_host', models.ForeignKey(blank=True, db_column='job_host_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_events', to='snmp_jobs.snmpjobhost')),
                ('olt', models.ForeignKey(blank=True, db_column='olt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_events', to='hosts.olt')),
                ('snmp_job', models.ForeignKey(blank=True, db_column='snmp_job_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_events', to='snmp_jobs.snmpjob')),
            ],
            options={
                'verbose_name': 'Evento del Coordinador',
                'verbose_name_plural': 'Eventos del Coordinador',
                'db_table': 'coordinator_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='coordinator_created_66564c_idx'), models.Index(fields=['event_type'], name='coordinator_event_t_10d31c_idx'), models.Index(fields=['decision'], name='coordinator_decisio_0d492d_idx'), models.Index(fields=['source'], name='coordinator_source_99cefc_idx'), models.Index(fields=['olt', 'created_at'], name='coordinator_olt_id_3b8d83_idx')],
            },
        ),
    ]
