# Generated by Django 4.2.16 on 2025-11-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution_coordinator', '0003_coordinatorevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotaviolation',
            name='olt',
        ),
        migrations.DeleteModel(
            name='QuotaTracker',
        ),
        migrations.DeleteModel(
            name='QuotaViolation',
        ),
    ]
