# Generated by Django 5.2.5 on 2025-08-30 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('oid', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'db_table': 'oids',
                'managed': True,
            },
        ),
    ]
