# Generated by Django 5.2.5 on 2025-10-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='espacio',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('descripcion', 'Descripción'), ('mac', 'MAC'), ('inventario', 'Inventario'), ('estado', 'Estado'), ('configuracion', 'Configuración'), ('estadisticas', 'Estadísticas'), ('otro', 'Otro')], default='descubrimiento', help_text='Tipo de información que proporciona este OID', max_length=20),
        ),
    ]
