# Generated by Django 5.2.5 on 2025-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0002_oid_espacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='format_mac',
            field=models.BooleanField(default=False, help_text='Elimina ":" y espacios de direcciones MAC (AC:DC:SD → ACDCSD)', verbose_name='Formatear MAC'),
        ),
        migrations.AddField(
            model_name='oid',
            name='keep_previous_value',
            field=models.BooleanField(default=False, help_text='Si está marcado, conserva el valor anterior cuando GET devuelve vacío (lógica facho_deluxe)', verbose_name='Mantener valor previo'),
        ),
        migrations.AddField(
            model_name='oid',
            name='target_field',
            field=models.CharField(blank=True, choices=[('snmp_description', 'Descripción SNMP'), ('mac_address', 'MAC Address'), ('plan_onu', 'Plan ONU'), ('distancia_onu', 'Distancia ONU'), ('modelo_onu', 'Modelo ONU'), ('serial_number', 'Serial Number'), ('subscriber_id', 'Subscriber ID')], help_text='Campo de onu_inventory donde se guardará el valor obtenido por GET', max_length=50, null=True, verbose_name='Campo destino en OnuInventory'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='espacio',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('descripcion', 'Descripción'), ('mac', 'MAC'), ('plan_onu', 'Plan ONU'), ('distancia_onu', 'Distancia ONU'), ('modelo_onu', 'Modelo ONU'), ('inventario', 'Inventario'), ('estado', 'Estado'), ('configuracion', 'Configuración'), ('estadisticas', 'Estadísticas'), ('otro', 'Otro')], default='descubrimiento', help_text='Tipo de información que proporciona este OID', max_length=20),
        ),
    ]
