# Generated by Django 5.2.5 on 2025-10-10 15:15

from django.db import migrations, models


def update_target_fields(apps, schema_editor):
    """Actualizar target_field automáticamente basado en espacio"""
    OID = apps.get_model('oids', 'OID')
    
    # Mapeo espacio → campo
    ESPACIO_TO_FIELD = {
        'descubrimiento': None,
        'descripcion': 'snmp_description',
        'mac': 'mac_address',
        'plan_onu': 'plan_onu',
        'distancia_onu': 'distancia_onu',
        'modelo_onu': 'modelo_onu',
        'serial': 'serial_number',
        'subscriber': 'subscriber_id',
    }
    
    for oid in OID.objects.all():
        oid.target_field = ESPACIO_TO_FIELD.get(oid.espacio)
        oid.save(update_fields=['target_field'])


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0003_add_get_config_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid',
            name='espacio',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('descripcion', 'Descripción'), ('mac', 'MAC Address'), ('plan_onu', 'Plan ONU'), ('distancia_onu', 'Distancia ONU'), ('modelo_onu', 'Modelo ONU'), ('serial', 'Serial Number'), ('subscriber', 'Subscriber ID')], default='descubrimiento', help_text='Tipo de información que proporciona este OID', max_length=20),
        ),
        migrations.AlterField(
            model_name='oid',
            name='target_field',
            field=models.CharField(blank=True, editable=False, help_text='Se asigna automáticamente según el espacio seleccionado', max_length=50, null=True, verbose_name='Campo destino (automático)'),
        ),
        migrations.RunPython(update_target_fields, reverse_code=migrations.RunPython.noop),
    ]
