# Generated by Django 4.2.16 on 2025-10-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('olt_models', '0002_add_sample_models'),
        ('oids', '0004_simplify_espacio_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='modelo',
            field=models.ForeignKey(blank=True, db_column='modelo_id', help_text='Modelo específico. Si está vacío, aplica a todos los modelos de la marca', null=True, on_delete=django.db.models.deletion.CASCADE, to='olt_models.oltmodel', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='espacio',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('descripcion', 'Descripción'), ('mac', 'MAC Address'), ('plan_onu', 'Plan ONU'), ('distancia_onu', 'Distancia ONU'), ('modelo_onu', 'Modelo ONU'), ('serial', 'Serial Number'), ('subscriber', 'Subscriber ID'), ('zabbix', 'Zabbix')], default='descubrimiento', help_text='Tipo de información que proporciona este OID', max_length=20),
        ),
        migrations.AlterField(
            model_name='oid',
            name='marca',
            field=models.ForeignKey(db_column='marca_id', help_text='Marca del equipo. Si es 🌐 Genérico, aplica a todas las marcas', on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Marca'),
        ),
    ]
