# Generated by Django 4.2.16 on 2025-10-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0005_add_modelo_and_zabbix_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid',
            name='espacio',
            field=models.CharField(choices=[('descubrimiento', 'Descubrimiento'), ('descripcion', 'Descripción'), ('mac', 'MAC Address'), ('plan_onu', 'Plan ONU'), ('distancia_onu', 'Distancia ONU'), ('modelo_onu', 'Modelo ONU'), ('serial', 'Serial Number'), ('subscriber', 'Subscriber ID'), ('zabbix_state', 'Zabbix - Estado Admin'), ('zabbix_interface', 'Zabbix - Nombre Interface'), ('zabbix_description', 'Zabbix - Descripción')], default='descubrimiento', help_text='Tipo de información que proporciona este OID', max_length=20),
        ),
    ]
