# Generated by Django 4.2.16 on 2025-10-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('oids', '0006_add_zabbix_oid_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid',
            name='marca',
            field=models.ForeignKey(blank=True, db_column='marca_id', help_text='Marca del equipo. Si está vacío (NULL), aplica a todas las marcas (genérico/universal)', null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Marca'),
        ),
    ]
