# Generated by Django 4.2.16 on 2025-11-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oids', '0008_alter_oid_marca_alter_oid_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oid',
            options={'managed': True, 'ordering': ['id']},
        ),
    ]
