# Generated by Django 5.2.5 on 2025-10-13 15:12

from django.db import migrations


def create_huawei_formula(apps, schema_editor):
    """
    Crea la fórmula de cálculo para equipos Huawei basada en la lógica actual.
    
    Fórmula Huawei:
    INDEX = 4194304000 + (slot × 8192) + (port × 256) + onu_id
    """
    IndexFormula = apps.get_model('snmp_formulas', 'IndexFormula')
    Brand = apps.get_model('brands', 'Brand')
    
    # Obtener marca Huawei (debe existir)
    try:
        huawei = Brand.objects.get(nombre__iexact='huawei')
    except Brand.DoesNotExist:
        print("⚠️ Marca Huawei no encontrada. Saltando creación de fórmula.")
        return
    
    # Crear fórmula Huawei
    IndexFormula.objects.get_or_create(
        marca=huawei,
        modelo=None,  # Fórmula genérica para toda la marca
        defaults={
            'nombre': 'Huawei - Fórmula Estándar',
            'activo': True,
            'calculation_mode': 'linear',
            'base_index': 4194304000,
            'step_slot': 8192,
            'step_port': 256,
            'onu_offset': 0,
            'has_dot_notation': True,
            'dot_is_onu_number': True,
            'slot_max': 64,
            'port_max': 64,
            'onu_max': 128,
            'normalized_format': '{slot}/{port}',
            'descripcion': 'Fórmula estándar para equipos Huawei. INDEX = 4194304000 + (slot × 8192) + (port × 256) + onu_id. El índice incluye notación con punto (.ONU) donde ONU es el número lógico.',
        }
    )
    print("✅ Fórmula Huawei creada exitosamente")


def reverse_huawei_formula(apps, schema_editor):
    """Elimina la fórmula de Huawei"""
    IndexFormula = apps.get_model('snmp_formulas', 'IndexFormula')
    Brand = apps.get_model('brands', 'Brand')
    
    try:
        huawei = Brand.objects.get(nombre__iexact='huawei')
        IndexFormula.objects.filter(marca=huawei, modelo__isnull=True).delete()
        print("✅ Fórmula Huawei eliminada")
    except Brand.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_formulas', '0001_initial'),
        ('brands', '__first__'),  # Asegurar que brands existe
    ]

    operations = [
        migrations.RunPython(create_huawei_formula, reverse_huawei_formula),
    ]
