# Generated by Django 5.2.5 on 2025-10-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt_models', '0001_initial'),
        ('snmp_formulas', '0002_add_huawei_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexformula',
            name='modelo',
            field=models.ForeignKey(blank=True, db_column='modelo_id', help_text='Modelo específico de OLT (opcional). Dejar vacío si aplica a toda la marca.', null=True, on_delete=django.db.models.deletion.CASCADE, to='olt_models.oltmodel', verbose_name='Modelo OLT'),
        ),
    ]
