# Generated by Django 5.2.5 on 2025-10-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('olt_models', '0002_add_sample_models'),
        ('snmp_formulas', '0003_alter_indexformula_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexformula',
            name='marca',
            field=models.ForeignKey(blank=True, db_column='marca_id', help_text='Marca del equipo (Huawei, ZTE, etc.). Dejar vacío para fórmula completamente genérica.', null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Marca'),
        ),
        migrations.AddConstraint(
            model_name='indexformula',
            constraint=models.CheckConstraint(check=models.Q(('marca__isnull', False), models.Q(('marca__isnull', True), ('modelo__isnull', True)), _connector='OR'), name='formula_generica_sin_marca_sin_modelo'),
        ),
    ]
