# Generated by Django 4.2.16 on 2025-10-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olt_models', '0002_add_sample_models'),
        ('brands', '0001_initial'),
        ('snmp_formulas', '0005_remove_constraint_alter_marca_modelo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indexformula',
            name='formula_generica_sin_marca_sin_modelo',
        ),
        migrations.AlterField(
            model_name='indexformula',
            name='marca',
            field=models.ForeignKey(db_column='marca_id', help_text='Marca del equipo. Use "🌐 Genérico" para fórmula universal.', on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='indexformula',
            name='modelo',
            field=models.ForeignKey(db_column='modelo_id', help_text='Modelo del equipo. Use "🌐 Genérico" si aplica a todos los modelos de la marca.', on_delete=django.db.models.deletion.CASCADE, to='olt_models.oltmodel', verbose_name='Modelo OLT'),
        ),
    ]
