# Generated by Django 5.2.5 on 2025-10-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del modelo de OLT (ej: MA5800, C320, AN5516-06)', max_length=100, unique=True, verbose_name='Nombre del modelo')),
                ('descripcion', models.TextField(help_text='Descripción técnica del modelo', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparecerá en las listas de selección', verbose_name='Activo')),
                ('tipo_olt', models.CharField(blank=True, help_text='Tipo de OLT (ej: GPON, EPON, XG-PON, XGS-PON)', max_length=50, null=True, verbose_name='Tipo de OLT')),
                ('capacidad_puertos', models.IntegerField(blank=True, help_text='Número máximo de puertos GPON/EPON soportados', null=True, verbose_name='Capacidad de puertos')),
                ('capacidad_onus', models.IntegerField(blank=True, help_text='Número máximo de ONUs soportadas por puerto', null=True, verbose_name='Capacidad de ONUs')),
                ('slots_disponibles', models.IntegerField(blank=True, help_text='Número de slots para tarjetas de línea', null=True, verbose_name='Slots disponibles')),
                ('version_firmware_minima', models.CharField(blank=True, help_text='Versión mínima de firmware requerida para SNMP', max_length=50, null=True, verbose_name='Versión firmware mínima')),
                ('comunidad_snmp_default', models.CharField(blank=True, help_text='Comunidad SNMP más común para este modelo', max_length=50, null=True, verbose_name='Comunidad SNMP por defecto')),
                ('puerto_snmp_default', models.IntegerField(blank=True, default=161, help_text='Puerto SNMP estándar (normalmente 161)', null=True, verbose_name='Puerto SNMP por defecto')),
                ('url_documentacion', models.URLField(blank=True, help_text='Enlace a la documentación técnica del modelo', null=True, verbose_name='URL de documentación')),
                ('url_manual_usuario', models.URLField(blank=True, help_text='Enlace al manual de usuario', null=True, verbose_name='URL manual de usuario')),
                ('notas_tecnicas', models.TextField(blank=True, help_text='Notas adicionales sobre configuración o características especiales', null=True, verbose_name='Notas técnicas')),
                ('soporte_tecnico_contacto', models.CharField(blank=True, help_text='Información de contacto para soporte técnico específico del modelo', max_length=255, null=True, verbose_name='Contacto soporte técnico')),
                ('fecha_lanzamiento', models.DateField(blank=True, help_text='Fecha aproximada de lanzamiento del modelo', null=True, verbose_name='Fecha de lanzamiento')),
                ('fecha_fin_soporte', models.DateField(blank=True, help_text='Fecha estimada de fin de soporte del fabricante', null=True, verbose_name='Fin de soporte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('marca', models.ForeignKey(db_column='marca_id', help_text='Marca del fabricante', on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de OLT',
                'verbose_name_plural': 'Modelos de OLT',
                'db_table': 'olt_models',
                'ordering': ['marca__nombre', 'nombre'],
                'indexes': [models.Index(fields=['marca', 'activo'], name='olt_models_marca_i_c90a17_idx'), models.Index(fields=['activo'], name='olt_models_activo_a24d7d_idx'), models.Index(fields=['nombre'], name='olt_models_nombre_f0b1ce_idx')],
            },
        ),
    ]
