# Generated by Django 5.2.5 on 2025-09-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('executions', '0003_remove_execution_attempts'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnuIndexMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_index_key', models.CharField(max_length=255)),
                ('slot', models.IntegerField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('logical', models.IntegerField(blank=True, null=True)),
                ('normalized_id', models.CharField(max_length=255)),
                ('marca_formula', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, to='hosts.olt')),
            ],
            options={
                'verbose_name': 'Mapeo de Índice ONU',
                'verbose_name_plural': 'Mapeos de Índices ONU',
                'db_table': 'onu_index_map',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnuInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=64, null=True)),
                ('subscriber_id', models.CharField(blank=True, max_length=255, null=True)),
                ('snmp_description', models.TextField(blank=True, null=True)),
                ('snmp_metadata', models.JSONField(blank=True, default=dict)),
                ('snmp_last_collected_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, to='hosts.olt')),
                ('onu_index', models.OneToOneField(db_column='onu_index_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='discovery.onuindexmap')),
                ('snmp_last_execution', models.ForeignKey(blank=True, db_column='snmp_last_execution_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='executions.execution')),
            ],
            options={
                'verbose_name': 'Inventario ONU',
                'verbose_name_plural': 'Inventario ONUs',
                'db_table': 'onu_inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnuStateLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('marca', models.ForeignKey(blank=True, db_column='marca_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'verbose_name': 'Estado ONU (Lookup)',
                'verbose_name_plural': 'Estados ONU (Lookup)',
                'db_table': 'onu_state_lookup',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='OnuStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_state_value', models.SmallIntegerField(blank=True, null=True)),
                ('last_state_label', models.CharField(blank=True, max_length=50, null=True)),
                ('presence', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=20)),
                ('consecutive_misses', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_change_execution', models.ForeignKey(blank=True, db_column='last_change_execution_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='executions.execution')),
                ('olt', models.ForeignKey(db_column='olt_id', on_delete=django.db.models.deletion.CASCADE, to='hosts.olt')),
                ('onu_index', models.OneToOneField(db_column='onu_index_id', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='discovery.onuindexmap')),
            ],
            options={
                'verbose_name': 'Estado Actual ONU',
                'verbose_name_plural': 'Estados Actuales ONU',
                'db_table': 'onu_status',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddIndex(
            model_name='onuindexmap',
            index=models.Index(fields=['olt', 'raw_index_key'], name='onu_index_m_olt_id_212e89_idx'),
        ),
        migrations.AddIndex(
            model_name='onuindexmap',
            index=models.Index(fields=['normalized_id'], name='onu_index_m_normali_755562_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onuindexmap',
            unique_together={('olt', 'raw_index_key')},
        ),
        migrations.AddIndex(
            model_name='onuinventory',
            index=models.Index(fields=['olt', 'active'], name='onu_invento_olt_id_f44d79_idx'),
        ),
        migrations.AddIndex(
            model_name='onuinventory',
            index=models.Index(fields=['serial_number'], name='onu_invento_serial__c10128_idx'),
        ),
        migrations.AddIndex(
            model_name='onuinventory',
            index=models.Index(fields=['mac_address'], name='onu_invento_mac_add_a80466_idx'),
        ),
        migrations.AddIndex(
            model_name='onustatus',
            index=models.Index(fields=['olt', 'presence'], name='onu_status_olt_id_d735e8_idx'),
        ),
        migrations.AddIndex(
            model_name='onustatus',
            index=models.Index(fields=['last_seen_at'], name='onu_status_last_se_6f65a0_idx'),
        ),
        migrations.AddIndex(
            model_name='onustatus',
            index=models.Index(fields=['consecutive_misses'], name='onu_status_consecu_0a49c7_idx'),
        ),
    ]
