# Generated by Django 5.2.5 on 2025-09-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
        ('odf_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onuindexmap',
            name='odf_hilo',
            field=models.ForeignKey(blank=True, db_column='odf_hilo_id', help_text='Enlaza el SNMPINDEX lógico con el puerto/hilo físico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='odf_management.odfhilos'),
        ),
    ]
