# Generated by Django 5.2.5 on 2025-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_onuindexmap_odf_hilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='onuinventory',
            name='distancia_onu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Distancia ONU'),
        ),
        migrations.AddField(
            model_name='onuinventory',
            name='modelo_onu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo ONU'),
        ),
        migrations.AddField(
            model_name='onuinventory',
            name='plan_onu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan ONU'),
        ),
    ]
