# Generated by Django 5.2.5 on 2025-10-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('discovery', '0003_add_plan_distancia_modelo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onustatelookup',
            name='value',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='onustatelookup',
            unique_together={('value', 'marca')},
        ),
        migrations.AddIndex(
            model_name='onustatelookup',
            index=models.Index(fields=['value', 'marca'], name='onu_state_l_value_30774e_idx'),
        ),
        migrations.AddIndex(
            model_name='onustatelookup',
            index=models.Index(fields=['marca'], name='onu_state_l_marca_i_1940c2_idx'),
        ),
    ]
