# Generated by Django 4.2.16 on 2025-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_fix_onu_state_lookup_unique'),
    ]

    operations = [
        # OnuInventoryInfo proxy model eliminado - ya no se usa
        # migrations.CreateModel(
        #     name='OnuInventoryInfo',
        #     fields=[
        #     ],
        #     options={
        #         'verbose_name': 'Información ONU',
        #         'verbose_name_plural': 'Información ONU',
        #         'proxy': True,
        #         'indexes': [],
        #         'constraints': [],
        #     },
        #     bases=('discovery.onuinventory',),
        # ),
        migrations.AlterField(
            model_name='onuinventory',
            name='active',
            field=models.BooleanField(default=True, help_text='Sincronizado manualmente con presence de OnuStatus por tareas SNMP'),
        ),
    ]
