# Generated by Django 5.2.5 on 2025-08-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('raw_output', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ejecución',
                'verbose_name_plural': 'Ejecuciones',
                'db_table': 'snmp_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('attempt_no', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Intento de Ejecución',
                'verbose_name_plural': 'Intentos de Ejecución',
                'db_table': 'execution_attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
