# Generated by Django 5.2.5 on 2025-08-30 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0001_initial'),
        ('hosts', '0001_initial'),
        ('snmp_jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='job_host',
            field=models.ForeignKey(blank=True, db_column='job_host_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp_jobs.snmpjobhost'),
        ),
        migrations.AddField(
            model_name='execution',
            name='olt',
            field=models.ForeignKey(blank=True, db_column='olt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hosts.olt'),
        ),
        migrations.AddField(
            model_name='execution',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='execution',
            name='snmp_job',
            field=models.ForeignKey(blank=True, db_column='snmp_job_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp_jobs.snmpjob'),
        ),
        migrations.AddField(
            model_name='executionattempt',
            name='execution',
            field=models.ForeignKey(db_column='execution_id', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='executions.execution'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['status', 'created_at'], name='snmp_execut_status_f1c7e0_idx'),
        ),
    ]
