# Generated by Django 5.2.5 on 2025-09-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutionAttempt',
        ),
    ]
