# Generated by Django 5.2.5 on 2025-09-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_remove_execution_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('INTERRUPTED', 'INTERRUPTED')], db_index=True, default='PENDING', max_length=16),
        ),
    ]
