# Generated by Django 4.2.16 on 2025-11-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_jobs', '0006_oltworkflow_taskfunction_tasktemplate_workflownode_and_more'),
        ('executions', '0004_add_interrupted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='workflow_node',
            field=models.ForeignKey(blank=True, db_column='workflow_node_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='snmp_jobs.workflownode'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['workflow_node'], name='snmp_execut_workflo_385fb6_idx'),
        ),
    ]
